StringLiterals:
  Enabled: false

MultilineBlocks:
  Enabled: false

SingleLineBlocks:
  Enabled: false

NewLambdaLiteral:
  Enabled: false

SpaceAroundEqualsInParameterDefault:
  Enabled: false

HashSyntax:
  Enabled: false
